/// Flutter icons MotionToastIcons
/// Copyright (C) 2021 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  MotionToastIcons
///      fonts:
///       - asset: fonts/MotionToastIcons.ttf
///
/// 
///
import 'package:flutter/widgets.dart';

class MotionToastIcons {
  MotionToastIcons._();

  static const _kFontFam = 'MotionToastIcons';
  static const String? _kFontPkg = null;

  static const IconData check = IconData(0xe800, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData warning__1_ = IconData(0xe805, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData error = IconData(0xe806, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData info = IconData(0xe807, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData delete = IconData(0xe808, fontFamily: _kFontFam, fontPackage: _kFontPkg);
}
