name: Feature request
description: Suggest a new idea for Motion Toast
body:
  - type: markdown
    attributes:
      value: |
        Thank you for using Motion Toast!
        
        You're feature request is important to us. Please provide as much information as possible 
        to help us understand the feature you're requesting. This will help us to implement it faster.
  - type: markdown
    attributes:
      value: |
        Before filling the form fields, please consider the following:
        - Ensure that you have searched the [existing issues](https://github.com/koukibadr/Motion-Toast/issues)
  - type: textarea
    attributes:
      label: Use case
      description: |
        Please tell us the problem you are running into that led to you wanting
        a new feature.

        Is your feature request related to a problem? Please give a clear and
        concise description of what the problem is.
    validations:
      required: true
  - type: textarea
    attributes:
      label: Proposal
      description: |
        Briefly but precisely describe what you would like the picker to be able to do.

        Consider attaching something showing what you are imagining:
         * images
         * videos
         * code samples
    validations:
      required: false
